name: Test
on: pull_request_target

permissions:
  checks: write
  pull-requests: write
  contents: write

jobs:
  test:
    permissions:
      checks: write
      pull-requests: write
      contents: write
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'npm'

      - name: Test
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          output: comment, report-markdown
